env:
  TERM: xterm-256color

  # https://github.com/alacritty/alacritty/issues/3424 --
  WINIT_X11_SCALE_FACTOR: "1"

scrolling:
  history: 5000

window:
  padding:
    x: 4
    y: 4

  dimensions:
    columns: 164
    lines: 42

colors:
  name: Chalk (dark)
  author: Chris Kempson
  primary:
    background: "#151515"
    foreground: "#d0d0d0"
  cursor:
    text: "#151515"
    cursor: "#d0d0d0"
  normal:
    black: "#151515"
    red: "#fb9fb1"
    green: "#acc267"
    yellow: "#ddb26f"
    blue: "#6fc2ef"
    magenta: "#e1a3ee"
    cyan: "#12cfc0"
    white: "#d0d0d0"
  bright:
    black: "#505050"
    red: "#fb9fb1"
    green: "#acc267"
    yellow: "#ddb26f"
    blue: "#6fc2ef"
    magenta: "#e1a3ee"
    cyan: "#12cfc0"
    white: "#f5f5f5"

font:
  normal:
    # family: Hack Nerd Font
    # family: Source Code Pro
    family: JetBrainsMono Nerd Font
    style: Regular

  bold:
    # family: Hack Nerd Font
    # family: Source Code Pro
    family: JetBrainsMono Nerd Font
    style: Bold

  italic:
    # family: Hack Nerd Font
    # family: Source Code Pro
    family: JetBrainsMono Nerd Font
    style: Italic

  bold_italic:
    # family: Hack Nerd Font
    # family: Source Code Pro
    family: JetBrainsMono Nerd Font
    style: Bold Italic

  size: 6

# Key bindings
Key_bindings:
  - { key: Equals, mods: Super, action: IncreaseFontSize }
  - { key: Subtract, mods: Super, action: DecreaseFontSize }
  - { key: Key0, mods: Super, action: ResetFontSize }
  - { key: PageUp, mods: Shift, action: ScrollPageUp }
  - { key: PageDown, mods: Shift, action: ScrollPageDown }
  - { key: End, mods: Shift, action: ScrollToBottom }
  - { key: Home, mods: Shift, action: ScrollToTop }
  - { key: V, mods: Control|Alt, action: Paste }
  - { key: C, mods: Control|Alt, action: Copy }
  - { key: Return, mods: Control, action: SpawnNewInstance }
  - { key: T, mods: Control, action: SpawnNewInstance }
theme: Chalk.dark
